import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { BrandMark } from "@/components/layout/brand";
import { buttonClass } from "@/components/ui/button";

const chapters = [["I","Aprender","Teoria explicada com exemplos que podem ser vistos e ouvidos."],["II","Praticar","Notas, escalas, tons e semitons no seu próprio ritmo."],["III","Ouvir","A escrita musical ligada ao som e ao teclado."],["IV","Criar","Uma folha aberta para montar seus próprios estudos."],["V","Registrar","Aulas, materiais e descobertas reunidos no mesmo caderno."]];

export function Welcome() {
  return <div className="min-h-dvh bg-paper">
    <header className="mx-auto flex w-full max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><div className="flex items-center gap-3 text-ink"><BrandMark className="size-8"/><span className="display text-base font-semibold">Caderno Musical</span></div><Link href="/entrar" className="text-sm text-ink-muted hover:text-ink">Entrar</Link></header>
    <main><section className="mx-auto grid min-h-[68vh] w-full max-w-6xl items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_.9fr] lg:py-24"><div><p className="mb-5 text-[.65rem] font-semibold tracking-[.18em] text-brass uppercase">Teoria · Volume I</p><h1 className="display max-w-3xl text-5xl leading-[.98] font-medium tracking-[-.045em] text-ink sm:text-6xl lg:text-7xl">Um lugar para entender, praticar e guardar música.</h1><p className="mt-7 max-w-xl text-base leading-7 text-ink-muted sm:text-lg">Seu caderno pessoal de teoria musical — calmo para aprender, preciso para estudar.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/entrar" className={buttonClass({variant:"solid",size:"lg"})}>Entrar <ArrowRight/></Link><Link href="/entrar#criar" className={buttonClass({variant:"ghost",size:"lg"})}>Criar conta</Link></div></div><MusicalLeaf/></section>
      <section className="border-t border-rule/70"><div className="mx-auto grid w-full max-w-6xl px-5 py-16 sm:px-8 md:grid-cols-2 lg:grid-cols-5">{chapters.map(([number,title,copy])=><article key={number} className="border-b border-rule/70 py-6 md:px-5 md:first:pl-0 lg:border-r lg:border-b-0 lg:last:border-r-0"><p className="font-mono text-[.625rem] text-brass">{number}</p><h2 className="display mt-3 text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{copy}</p></article>)}</div></section></main>
    <footer className="mx-auto flex w-full max-w-6xl justify-between border-t border-rule/70 px-5 py-7 text-xs text-ink-faint sm:px-8"><span>Caderno Musical</span><span>Teoria · Volume I</span></footer>
  </div>;
}

function MusicalLeaf() { const notes=[{x:130,y:128},{x:190,y:120},{x:250,y:112},{x:310,y:104},{x:370,y:96},{x:430,y:88},{x:490,y:80},{x:550,y:72}]; return <figure className="mx-auto w-full max-w-xl border-y border-rule/80 py-10" aria-label="Escala de Dó maior"><figcaption className="mb-7 flex items-baseline justify-between"><span className="display text-xl font-semibold">Uma escala, escrita.</span><span className="font-mono text-[.625rem] tracking-widest text-ink-faint">DÓ MAIOR</span></figcaption><svg viewBox="0 0 620 180" role="img" aria-label="Escala de Dó maior em um pentagrama" className="w-full text-ink">{[56,72,88,104,120].map(y=><line key={y} x1="20" x2="600" y1={y} y2={y} stroke="currentColor" opacity=".55"/>)}<text x="30" y="116" fontSize="74" fontFamily="serif" fill="currentColor">𝄞</text>{notes.map((n,i)=><g key={i}><ellipse cx={n.x} cy={n.y} rx="8" ry="5.5" transform={`rotate(-16 ${n.x} ${n.y})`} fill="currentColor"/><line x1={n.x+7} x2={n.x+7} y1={n.y} y2={n.y-35} stroke="currentColor" strokeWidth="2"/></g>)}</svg><div className="mt-5 flex justify-between font-mono text-[.65rem] tracking-[.12em] text-ink-muted"><span>DÓ · RÉ · MI · FÁ · SOL · LÁ · SI · DÓ</span><span className="hidden sm:block">T–T–ST–T–T–T–ST</span></div></figure>; }
