import test from "node:test";import assert from "node:assert/strict";import { buildDiatonicTriad,buildTriad,chordSymbol,TRIAD_QUALITIES } from "@/lib/music/chords";import { note,noteName } from "@/lib/music/notes";import { buildMajorScale } from "@/lib/music/scales";import { chordSchedule,voiceGain } from "@/lib/music/audio";
const names=(root:Parameters<typeof buildTriad>[0],quality:Parameters<typeof buildTriad>[1],inversion:Parameters<typeof buildTriad>[2]="root")=>buildTriad(root,quality,inversion).pitches.map(noteName);
test("tríades maiores preservam grafia",()=>{assert.deepEqual(names(note("C"),"major"),["Dó","Mi","Sol"]);assert.deepEqual(names(note("D"),"major"),["Ré","Fá♯","Lá"]);assert.deepEqual(names(note("F"),"major"),["Fá","Lá","Dó"]);assert.deepEqual(names(note("B",-1),"major"),["Si♭","Ré","Fá"]);});
test("tríades menores preservam grafia",()=>{assert.deepEqual(names(note("C"),"minor"),["Dó","Mi♭","Sol"]);assert.deepEqual(names(note("D"),"minor"),["Ré","Fá","Lá"]);assert.deepEqual(names(note("E"),"minor"),["Mi","Sol","Si"]);assert.deepEqual(names(note("A"),"minor"),["Lá","Dó","Mi"]);});
test("qualidades têm intervalos corretos",()=>{assert.deepEqual(TRIAD_QUALITIES.major.intervals,["M3","P5"]);assert.deepEqual(TRIAD_QUALITIES.minor.intervals,["m3","P5"]);assert.deepEqual(TRIAD_QUALITIES.diminished.intervals,["m3","d5"]);assert.deepEqual(TRIAD_QUALITIES.augmented.intervals,["M3","A5"]);assert.deepEqual(buildTriad(note("C"),"major").stackedThirds,["M3","m3"]);assert.deepEqual(buildTriad(note("C"),"minor").stackedThirds,["m3","M3"]);});
test("inversões preservam identidade",()=>{assert.deepEqual(names(note("C"),"major","root"),["Dó","Mi","Sol"]);assert.deepEqual(names(note("C"),"major","first"),["Mi","Sol","Dó"]);assert.deepEqual(names(note("C"),"major","second"),["Sol","Dó","Mi"]);});
test("cifras separam símbolo internacional",()=>{assert.equal(chordSymbol(note("C"),"major"),"C");assert.equal(chordSymbol(note("C"),"minor"),"Cm");assert.equal(chordSymbol(note("F"),"major"),"F");assert.equal(chordSymbol(note("A"),"minor"),"Am");});
test("tríades diatônicas derivam das notas da escala",()=>{const qualities=["major","minor","minor","major","major","minor","diminished"];const c=buildMajorScale(note("C"));assert.deepEqual(c.map((_,i)=>buildDiatonicTriad(c,i+1).quality),qualities);const g=buildMajorScale(note("G"));assert.deepEqual(buildDiatonicTriad(g,5).pitches.map(noteName),["Ré","Fá♯","Lá"]);const f=buildMajorScale(note("F"));assert.ok(f.flatMap((_,i)=>buildDiatonicTriad(f,i+1).pitches).some(n=>noteName(n)==="Si♭"));});
test("áudio agenda acorde e arpejos com ganho seguro",()=>{const triad=buildTriad(note("C"),"major");assert.ok(voiceGain(3)<voiceGain(2));assert.deepEqual(chordSchedule(triad.pitches).map(x=>x.startTime),[0,0,0]);assert.deepEqual(chordSchedule(triad.pitches,"up").map(x=>noteName(x.note)),["Dó","Mi","Sol"]);assert.deepEqual(chordSchedule(triad.pitches,"down").map(x=>noteName(x.note)),["Sol","Mi","Dó"]);});
