import { note } from '@/lib/music/notes';
import type { ScheduledTone } from '@/lib/music/audio';
export type RhythmValue='whole'|'half'|'quarter'|'eighth';
export type Meter={numerator:2|3|4;denominator:4};
export type RhythmEvent={value:RhythmValue;rest?:boolean};
export type RhythmPattern={id:string;meter:Meter;events:RhythmEvent[];label:string};
export const RHYTHM_VALUES:Record<RhythmValue,{name:string;ticks:number;beats:number}>={whole:{name:'Semibreve',ticks:8,beats:4},half:{name:'Mínima',ticks:4,beats:2},quarter:{name:'Semínima',ticks:2,beats:1},eighth:{name:'Colcheia',ticks:1,beats:.5}};
export const RHYTHM_ORDER:RhythmValue[]=['whole','half','quarter','eighth'];
export const RHYTHM_AUDIO_PROFILE={clickDuration:.075,accentGain:.82,clickGain:.55,lookAheadSeconds:.08} as const;
export function measureTicks(meter:Meter){return meter.numerator*(8/meter.denominator);}
export function patternTicks(pattern:RhythmPattern){return pattern.events.reduce((sum,event)=>sum+RHYTHM_VALUES[event.value].ticks,0);}
export function validateMeasure(pattern:RhythmPattern):'complete'|'incomplete'|'overflow'{const actual=patternTicks(pattern),expected=measureTicks(pattern.meter);return actual===expected?'complete':actual<expected?'incomplete':'overflow';}
export function beatSeconds(bpm:number){return 60/Math.max(40,Math.min(180,bpm));}
export type ScheduledRhythmEvent={event:RhythmEvent;startBeat:number;durationBeats:number;accent:boolean};
export function scheduleRhythm(pattern:RhythmPattern,countIn=0):ScheduledRhythmEvent[]{let cursor=countIn;return pattern.events.map((event,index)=>{const durationBeats=RHYTHM_VALUES[event.value].beats;const scheduled={event,startBeat:cursor,durationBeats,accent:index===0};cursor+=durationBeats;return scheduled;});}
export function rhythmTones(pattern:RhythmPattern,bpm:number,countIn=0):ScheduledTone[]{const seconds=beatSeconds(bpm);const count:Array<ScheduledTone>=Array.from({length:countIn},(_,index)=>({note:index===0?note('C',0,5):note('A'),startTime:index*seconds,duration:RHYTHM_AUDIO_PROFILE.clickDuration,gain:index===0?RHYTHM_AUDIO_PROFILE.accentGain:RHYTHM_AUDIO_PROFILE.clickGain}));const events=scheduleRhythm(pattern,countIn).filter(item=>!item.event.rest).map(item=>({note:item.accent?note('C',0,5):note('A'),startTime:item.startBeat*seconds,duration:Math.min(.12,item.durationBeats*seconds*.35),gain:item.accent?RHYTHM_AUDIO_PROFILE.accentGain:RHYTHM_AUDIO_PROFILE.clickGain}));return[...count,...events];}
export type TapAnalysis={variationMs:number;offsetMs:number;status:'estável'|'razoavelmente estável'|'merece praticar';missing:number;extra:number};
export function analyzeTaps(expected:number[],actual:number[]):TapAnalysis{if(!actual.length)return{variationMs:0,offsetMs:0,status:'merece praticar',missing:expected.length,extra:0};const count=Math.min(expected.length,actual.length);const offsets=Array.from({length:count},(_,i)=>actual[i]-expected[i]);const offset=offsets.reduce((a,b)=>a+b,0)/offsets.length;const variance=offsets.reduce((sum,value)=>sum+(value-offset)**2,0)/offsets.length;const variation=Math.sqrt(variance);return{variationMs:Math.round(variation),offsetMs:Math.round(offset),status:variation<=70?'estável':variation<=140?'razoavelmente estável':'merece praticar',missing:Math.max(0,expected.length-actual.length),extra:Math.max(0,actual.length-expected.length)};}
export const RHYTHM_PATTERNS:RhythmPattern[]=[{id:'quarters',meter:{numerator:4,denominator:4},label:'Quatro semínimas',events:Array.from({length:4},()=>({value:'quarter'}))},{id:'half-quarters',meter:{numerator:4,denominator:4},label:'Mínima e duas semínimas',events:[{value:'half'},{value:'quarter'},{value:'quarter'}]},{id:'eighths',meter:{numerator:4,denominator:4},label:'Oito colcheias',events:Array.from({length:8},()=>({value:'eighth'}))},{id:'rest-third',meter:{numerator:4,denominator:4},label:'Pausa no terceiro tempo',events:[{value:'quarter'},{value:'quarter'},{value:'quarter',rest:true},{value:'quarter'}]}];
