"use client";

import * as React from "react";
import Link from "next/link";
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock, Download, MapPin, Plus, Trash2 } from "lucide-react";
import { Button, buttonClass } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/field";
import { Modal } from "@/components/ui/overlay";
import { EmptyState, SectionHeading } from "@/components/ui/prose";
import { EMPTY_BOARDS } from "@/lib/atelier/types";
import { dateKey, EVENT_LABEL, expandRecurringEvent, localDateTime, NO_EVENTS, type EventType, type StudyEvent, type Understanding } from "@/lib/agenda/types";
import { KEYS } from "@/lib/storage/local";
import { NO_MATERIAL, NO_NOTES } from "@/lib/storage/types";
import { usePersistentState } from "@/lib/storage/use-persistent-state";
import { EMPTY_STUDY_STATE } from "@/lib/storage/types";
import { uid } from "@/lib/utils";

type View = "upcoming" | "today" | "month" | "journey";
const dateFmt = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric" });
const weekdayFmt = new Intl.DateTimeFormat("pt-BR", { weekday: "long", day: "2-digit", month: "long" });
const timeFmt = new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" });
const monthFmt = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" });

export function AgendaStudio() {
  const { value: events, set: setEvents, ready } = usePersistentState<StudyEvent[]>(KEYS.agenda, NO_EVENTS);
  const { value: notes } = usePersistentState(KEYS.notebook, NO_NOTES);
  const { value: materials } = usePersistentState(KEYS.material, NO_MATERIAL);
  const { value: boards } = usePersistentState(KEYS.atelier, EMPTY_BOARDS);
  const { value: study } = usePersistentState(KEYS.study, EMPTY_STUDY_STATE);
  const [view,setView]=React.useState<View>("upcoming"); const [editing,setEditing]=React.useState(false); const [activeId,setActiveId]=React.useState<string|null>(null); const [filter,setFilter]=React.useState<"all"|EventType>("all"); const [query,setQuery]=React.useState(""); const [month,setMonth]=React.useState(()=>new Date());
  const [now] = React.useState(() => Date.now());
  const active=events.find(e=>e.id===activeId)??null;
  const visible=React.useMemo(()=>events.filter(e=>(filter==="all"||e.type===filter)&&(`${e.title} ${e.topic}`).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.startAt.localeCompare(b.startAt)),[events,filter,query]);
  const reminders=events.filter(e=>e.status==="planned"&&e.reminders.inApp&&new Date(e.startAt).getTime()>=now&&new Date(e.startAt).getTime()-now<=86400000);
  const update=(id:string, patch:Partial<StudyEvent>)=>setEvents(items=>items.map(e=>e.id===id?{...e,...patch,updatedAt:Date.now()}:e));
  const remove=(id:string)=>{setEvents(items=>items.filter(e=>e.id!==id));setActiveId(null);};

  if(active) return <LessonPage event={active} events={events} notes={notes} materials={materials} boards={boards} onBack={()=>setActiveId(null)} onUpdate={patch=>update(active.id,patch)} onRemove={()=>remove(active.id)} onAdd={event=>setEvents(items=>[...items,event])}/>;
  return <div className="flex flex-col gap-8"><SectionHeading eyebrow="Minha jornada no tempo" title="Agenda" description="Planeje, prepare, registre e transforme cada aula no próximo passo do seu estudo."><Button variant="brass" onClick={()=>setEditing(true)}><Plus/> Novo compromisso</Button></SectionHeading>
    {reminders.length?<div className="border-y border-rule py-4"><p className="type-label text-brass">{dateKey(new Date(reminders[0].startAt))===dateKey(new Date())?"Hoje":"Amanhã"}</p><button className="mt-2 text-left" onClick={()=>setActiveId(reminders[0].id)}><span className="display font-semibold">{reminders[0].title}</span><span className="ml-2 text-sm text-ink-muted">· {timeFmt.format(new Date(reminders[0].startAt))}</span></button></div>:null}
    <div className="flex gap-5 overflow-x-auto border-b border-rule" role="tablist">{([['upcoming','Próximos'],['today','Hoje'],['month','Mês'],['journey','Minha jornada']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={view===id} onClick={()=>setView(id)} className={`shrink-0 border-b-2 px-1 pb-3 text-sm ${view===id?'border-brass font-semibold text-ink':'border-transparent text-ink-muted'}`}>{label}</button>)}</div>
    <div className="flex flex-wrap items-center gap-2"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar título ou assunto" aria-label="Buscar na agenda" className="max-w-xs"/><div className="flex gap-1">{([['all','Tudo'],['lesson','Aulas'],['study','Estudos'],['review','Revisões']] as const).map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`min-h-9 px-3 text-xs ${filter===id?'font-semibold text-ink underline decoration-brass underline-offset-4':'text-ink-muted'}`}>{label}</button>)}</div></div>
    {!ready?<p className="py-20 text-center text-sm text-ink-faint">Abrindo a agenda…</p>:events.length===0?<EmptyState icon={<CalendarDays/>} title="Sua agenda começa aqui" description="Registre sua próxima aula para reunir preparação, materiais e anotações num só lugar."><Button variant="brass" onClick={()=>setEditing(true)}>Adicionar aula</Button></EmptyState>:view==="upcoming"?<Upcoming events={visible.filter(e=>new Date(e.startAt).getTime()>=now-86400000)} onOpen={setActiveId}/>:view==="today"?<Today events={visible} attempts={study.attempts}/>:view==="month"?<MonthView events={visible} month={month} setMonth={setMonth} onOpen={setActiveId}/>:<Journey events={visible}/>} 
    {events.length ? <Weekly events={events} study={study} now={now} /> : null}
    <EventModal open={editing} onClose={()=>setEditing(false)} onSave={created=>{setEvents(items=>[...items,...created]);setEditing(false);}}/>
  </div>;
}

function Weekly({events,study,now}:{events:StudyEvent[];study:typeof EMPTY_STUDY_STATE;now:number}) { const current=new Date(now);const monday=new Date(current);monday.setDate(current.getDate()-((current.getDay()+6)%7));monday.setHours(0,0,0,0);const end=new Date(monday);end.setDate(end.getDate()+7);const week=events.filter(e=>new Date(e.startAt)>=monday&&new Date(e.startAt)<end);const attempts=study.attempts.filter(a=>a.ts>=monday.getTime()&&a.ts<end.getTime());const topics=new Map<string,number>();for(const event of week)if(event.topic)topics.set(event.topic,(topics.get(event.topic)??0)+1);const topic=[...topics].sort((a,b)=>b[1]-a[1])[0]?.[0]??"—";const difficulty=Object.values(study.errors).sort((a,b)=>b.misses-a.misses)[0]?.prompt??"—";const pending=week.flatMap(e=>e.homework).filter(i=>!i.done).length;return <section className="border-t border-rule pt-7"><p className="type-label text-ink-faint">Esta semana</p><dl className="mt-5 grid grid-cols-2 gap-y-5 sm:grid-cols-3 lg:grid-cols-6"><Mini label="Aulas" value={week.filter(e=>e.type==='lesson').length}/><Mini label="Estudos" value={week.filter(e=>e.type==='study'||e.type==='review').length}/><Mini label="Exercícios" value={attempts.length}/><Mini label="Tópico principal" value={topic}/><Mini label="Dificuldade" value={difficulty}/><Mini label="Pendências" value={pending}/></dl></section>;}
function Mini({label,value}:{label:string;value:string|number}) { return <div className="border-l border-rule pl-3"><dt className="type-label text-ink-faint">{label}</dt><dd className="display mt-2 text-lg font-semibold">{value}</dd></div>; }

function Upcoming({events,onOpen}:{events:StudyEvent[];onOpen:(id:string)=>void}) { return <div className="divide-y divide-rule border-y border-rule">{events.map(e=><button key={e.id} onClick={()=>onOpen(e.id)} className="grid w-full grid-cols-[3.5rem_1fr_auto] items-center gap-4 py-5 text-left hover:bg-paper-raised/60"><div className="text-center"><span className="display block text-2xl">{new Date(e.startAt).getDate()}</span><span className="type-label text-ink-faint">{new Date(e.startAt).toLocaleDateString('pt-BR',{month:'short'})}</span></div><div><span className="type-label text-brass">{EVENT_LABEL[e.type]}</span><p className="display mt-1 text-lg font-semibold">{e.title}</p><p className="mt-1 text-xs text-ink-muted">{e.topic||e.teacher||"Sem assunto definido"}</p></div><span className="type-technical text-xs text-ink-muted">{timeFmt.format(new Date(e.startAt))}</span></button>)}</div>; }

function Today({events,attempts}:{events:StudyEvent[];attempts:{ts:number}[]}) { const today=dateKey(new Date()); const items=events.filter(e=>dateKey(new Date(e.startAt))===today); const done=items.filter(e=>e.status==='completed'); return <div className="grid gap-10 md:grid-cols-2"><section><p className="type-label text-ink-faint">Próximo compromisso</p>{items.find(e=>e.status==='planned')?<p className="display mt-3 text-2xl">{items.find(e=>e.status==='planned')!.title}</p>:<p className="mt-3 text-sm text-ink-muted">Nenhum compromisso restante hoje.</p>}</section><section><p className="type-label text-ink-faint">O estudo de hoje</p><p className="display mt-3 text-2xl">{attempts.filter(a=>dateKey(new Date(a.ts))===today).length} exercícios</p><p className="mt-1 text-sm text-ink-muted">{done.length} {done.length===1?'sessão concluída':'sessões concluídas'}.</p></section></div>; }

function MonthView({events,month,setMonth,onOpen}:{events:StudyEvent[];month:Date;setMonth:(d:Date)=>void;onOpen:(id:string)=>void}) { const first=new Date(month.getFullYear(),month.getMonth(),1); const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); const cells=[...Array(first.getDay()).fill(null),...Array.from({length:days},(_,i)=>i+1)]; return <div><div className="mb-5 flex items-center justify-between"><Button variant="ghost" size="icon" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} aria-label="Mês anterior"><ChevronLeft/></Button><h2 className="display text-xl font-semibold capitalize">{monthFmt.format(month)}</h2><Button variant="ghost" size="icon" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} aria-label="Próximo mês"><ChevronRight/></Button></div><div className="grid grid-cols-7 border-t border-l border-rule">{cells.map((day,i)=>{const key=day?dateKey(new Date(month.getFullYear(),month.getMonth(),day)):'';const dayEvents=events.filter(e=>dateKey(new Date(e.startAt))===key);return <div key={i} className="min-h-20 border-r border-b border-rule p-2"><span className="text-xs text-ink-muted">{day}</span>{dayEvents.slice(0,2).map(e=><button key={e.id} onClick={()=>onOpen(e.id)} className="mt-1 block w-full truncate border-l border-brass pl-1 text-left text-[.65rem] text-ink">{e.title}</button>)}</div>})}</div></div>; }

function Journey({events}:{events:StudyEvent[]}) { const complete=[...events].filter(e=>e.status==='completed').sort((a,b)=>b.startAt.localeCompare(a.startAt)); return <div className="border-l border-rule pl-6">{complete.length?complete.map(e=><article key={e.id} className="relative pb-10"><span className="absolute -left-[1.72rem] top-1 size-2 rounded-full bg-brass"/><p className="type-label text-ink-faint">{dateFmt.format(new Date(e.startAt))}</p><h2 className="display mt-2 text-xl font-semibold">{e.topic||e.title}</h2>{e.reflection.learned?<p className="mt-3 text-sm leading-6"><span className="text-ink-faint">Aprendi: </span>{e.reflection.learned}</p>:null}{e.reflection.difficult?<p className="mt-1 text-sm leading-6"><span className="text-ink-faint">Ainda difícil: </span>{e.reflection.difficult}</p>:null}</article>):<p className="text-sm text-ink-muted">A jornada aparece aqui quando você conclui uma aula ou sessão.</p>}</div>; }

function EventModal({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(e:StudyEvent[])=>void}) { const now=new Date(); const [type,setType]=React.useState<EventType>('lesson'); const [title,setTitle]=React.useState('Aula de Teoria Musical'); const [date,setDate]=React.useState(dateKey(now)); const [start,setStart]=React.useState('19:00'); const [end,setEnd]=React.useState('20:00'); const [topic,setTopic]=React.useState(''); const [teacher,setTeacher]=React.useState(''); const [location,setLocation]=React.useState(''); const [note,setNote]=React.useState(''); const [repeat,setRepeat]=React.useState<'none'|'weekly'|'biweekly'>('none'); const [until,setUntil]=React.useState('');
  function save(){const createdAt=Date.now();const id=uid();const recurrence=repeat==='none'?null:{frequency:repeat,seriesId:id,until:until||null} as const;const base:StudyEvent={id,type,title:title.trim(),startAt:localDateTime(date,start).toISOString(),endAt:localDateTime(date,end).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,location,teacher,topic,note,status:'planned',recurrence,reminders:{inApp:true,offsets:[1440,60],email:false},preparation:{review:'',questions:[]},content:{subjects:'',notes:'',examples:'',exercises:'',concepts:''},reflection:{learned:'',difficult:'',practiceNext:'',questionsNext:'',understanding:null,completedAt:null},homework:[],resources:[],createdAt,updatedAt:createdAt};onSave(recurrence?expandRecurringEvent(base,until||null):[base]);}
  return <Modal open={open} onClose={onClose} title="Novo compromisso" description="Uma data para preparar, estudar e registrar." size="lg" footer={<><Button variant="ghost" onClick={onClose}>Cancelar</Button><Button variant="brass" onClick={save} disabled={!title.trim()}>Adicionar à agenda</Button></>}><div className="grid gap-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><Select value={type} onChange={e=>setType(e.target.value as EventType)}><option value="lesson">Aula</option><option value="study">Estudo</option><option value="review">Revisão</option></Select></Field><Field label="Título"><Input value={title} onChange={e=>setTitle(e.target.value)}/></Field></div><div className="grid grid-cols-3 gap-3"><Field label="Data"><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Início"><Input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Fim"><Input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Assunto"><Input value={topic} onChange={e=>setTopic(e.target.value)}/></Field><Field label="Professor(a)"><Input value={teacher} onChange={e=>setTeacher(e.target.value)}/></Field><Field label="Local"><Input value={location} onChange={e=>setLocation(e.target.value)}/></Field><Field label="Recorrência"><Select value={repeat} onChange={e=>setRepeat(e.target.value as typeof repeat)}><option value="none">Não repetir</option><option value="weekly">Toda semana</option><option value="biweekly">A cada duas semanas</option></Select></Field></div>{repeat!=='none'?<Field label="Repetir até" hint="Opcional; sem data final, cria dois anos de ocorrências."><Input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></Field>:null}<Field label="Observação"><Textarea value={note} onChange={e=>setNote(e.target.value)}/></Field></div></Modal>;
}

function LessonPage({event,events,notes,materials,boards,onBack,onUpdate,onRemove,onAdd}:{event:StudyEvent;events:StudyEvent[];notes:typeof NO_NOTES;materials:typeof NO_MATERIAL;boards:typeof EMPTY_BOARDS;onBack:()=>void;onUpdate:(p:Partial<StudyEvent>)=>void;onRemove:()=>void;onAdd:(e:StudyEvent)=>void}) { const [closing,setClosing]=React.useState(false); const previous=[...events].filter(e=>e.type==='lesson'&&e.startAt<event.startAt&&e.id!==event.id).sort((a,b)=>b.startAt.localeCompare(a.startAt))[0]; const patchSection=(key:'preparation'|'content'|'reflection',field:string,value:unknown)=>onUpdate({[key]:{...event[key],[field]:value}});
  function addQuestion(){patchSection('preparation','questions',[...event.preparation.questions,{id:uid(),text:'Nova dúvida',done:false}]);} function addHomework(){onUpdate({homework:[...event.homework,{id:uid(),text:'Novo item de prática',done:false}]});}
  function exportIcs(){const stamp=(iso:string)=>new Date(iso).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Caderno Musical//Agenda V1.5//PT','BEGIN:VEVENT',`UID:${event.id}@caderno-musical`,`DTSTART:${stamp(event.startAt)}`,`DTEND:${stamp(event.endAt)}`,`SUMMARY:${event.title.replace(/[,;]/g,' ')}`,`DESCRIPTION:${(event.topic||event.note).replace(/\n/g,'\\n')}`,`LOCATION:${event.location.replace(/[,;]/g,' ')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download=`${event.title.replace(/[^a-z0-9]/gi,'-').toLowerCase()}.ics`;a.click();URL.revokeObjectURL(url);}
  return <div className="flex flex-col gap-10"><button onClick={onBack} className="flex items-center gap-2 self-start text-sm text-ink-muted hover:text-ink"><ChevronLeft className="size-4"/> Voltar à agenda</button><header className="border-b border-rule pb-7"><p className="type-label text-brass">{EVENT_LABEL[event.type]} · {event.status==='completed'?'Concluída':event.status==='cancelled'?'Cancelada':'Planejada'}</p><h1 className="display mt-3 text-4xl font-medium">{event.title}</h1><p className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-ink-muted"><span><Clock className="mr-1 inline size-4"/>{weekdayFmt.format(new Date(event.startAt))} · {timeFmt.format(new Date(event.startAt))}–{timeFmt.format(new Date(event.endAt))}</span>{event.location?<span><MapPin className="mr-1 inline size-4"/>{event.location}</span>:null}{event.teacher?<span>{event.teacher}</span>:null}</p><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={exportIcs}><Download/> Adicionar ao calendário</Button>{event.status==='planned'?<Button variant="ghost" size="sm" onClick={()=>onUpdate({status:'cancelled'})}>Cancelar</Button>:null}<Button variant="ghost" size="sm" onClick={onRemove}><Trash2/> Excluir</Button></div></header>
    <details className="border-b border-rule pb-6"><summary className="cursor-pointer text-sm font-medium text-ink-muted">Editar dados desta ocorrência</summary><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Título"><Input defaultValue={event.title} onBlur={e=>onUpdate({title:e.target.value.trim()||event.title})}/></Field><Field label="Assunto"><Input defaultValue={event.topic} onBlur={e=>onUpdate({topic:e.target.value})}/></Field><Field label="Professor(a)"><Input defaultValue={event.teacher} onBlur={e=>onUpdate({teacher:e.target.value})}/></Field><Field label="Local"><Input defaultValue={event.location} onBlur={e=>onUpdate({location:e.target.value})}/></Field><Field label="Início"><Input type="datetime-local" defaultValue={toLocalInput(event.startAt)} onBlur={e=>{const start=new Date(e.target.value);if(!Number.isNaN(start.getTime()))onUpdate({startAt:start.toISOString()});}}/></Field><Field label="Fim"><Input type="datetime-local" defaultValue={toLocalInput(event.endAt)} onBlur={e=>{const end=new Date(e.target.value);if(!Number.isNaN(end.getTime()))onUpdate({endAt:end.toISOString()});}}/></Field></div></details>
    {previous?.homework.length?<section><p className="type-label text-ink-faint">Da aula anterior</p><p className="mt-2 text-sm text-ink-muted">{previous.homework.filter(i=>i.done).length} de {previous.homework.length} itens concluídos.</p></section>:null}
    <PageSection number="I" title="Antes da aula" subtitle="Preparação"><Field label="O que quero revisar antes?"><Textarea className="ruled-paper" value={event.preparation.review} onChange={e=>patchSection('preparation','review',e.target.value)}/></Field><Checklist title="Dúvidas para perguntar" items={event.preparation.questions} onChange={questions=>patchSection('preparation','questions',questions)} onAdd={addQuestion}/><Resources event={event} notes={notes} materials={materials} boards={boards} onUpdate={onUpdate}/></PageSection>
    <PageSection number="II" title="Durante a aula" subtitle="Conteúdo"><Writing label="Assuntos estudados" value={event.content.subjects} onChange={v=>patchSection('content','subjects',v)}/><Writing label="Anotações rápidas" value={event.content.notes} onChange={v=>patchSection('content','notes',v)}/><Writing label="Exemplos importantes" value={event.content.examples} onChange={v=>patchSection('content','examples',v)}/><Writing label="Exercícios passados" value={event.content.exercises} onChange={v=>patchSection('content','exercises',v)}/><Writing label="Conceitos mencionados" value={event.content.concepts} onChange={v=>patchSection('content','concepts',v)}/></PageSection>
    <PageSection number="III" title="Depois da aula" subtitle="Próximos passos"><Checklist title="Até a próxima aula" items={event.homework} onChange={homework=>onUpdate({homework})} onAdd={addHomework}/>{event.status!=='completed'?<Button variant="brass" onClick={()=>setClosing(true)}><Check/> Concluir aula</Button>:<Reflection event={event} patch={patchSection} onSchedule={()=>scheduleReview(event,onAdd)}/>}</PageSection>
    <Modal open={closing} onClose={()=>setClosing(false)} title="Fechar esta aula" description="Um minuto para registrar o que fica." size="lg" footer={<><Button variant="ghost" onClick={()=>setClosing(false)}>Voltar</Button><Button variant="brass" onClick={()=>{onUpdate({status:'completed',reflection:{...event.reflection,completedAt:Date.now()}});setClosing(false);}}>Concluir aula</Button></>}><Reflection event={event} patch={patchSection}/></Modal>
  </div>;
}

function toLocalInput(isoValue:string) { const date=new Date(isoValue);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16); }

function PageSection({number,title,subtitle,children}:{number:string;title:string;subtitle:string;children:React.ReactNode}) { return <section className="grid gap-6 border-t border-rule pt-8 md:grid-cols-[10rem_1fr]"><div><p className="type-label text-brass">{number} · {subtitle}</p><h2 className="display mt-2 text-2xl font-semibold">{title}</h2></div><div className="flex flex-col gap-6">{children}</div></section>; }
function Writing({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <Field label={label}><Textarea className="ruled-paper min-h-24 border-x-0 border-t-0 rounded-none" value={value} onChange={e=>onChange(e.target.value)}/></Field>; }
function Checklist({title,items,onChange,onAdd}:{title:string;items:{id:string;text:string;done:boolean}[];onChange:(i:typeof items)=>void;onAdd:()=>void}) { return <div><p className="type-label text-ink-muted">{title}</p><div className="mt-3 divide-y divide-rule">{items.map(item=><div key={item.id} className="flex items-center gap-3 py-2"><input type="checkbox" checked={item.done} onChange={e=>onChange(items.map(i=>i.id===item.id?{...i,done:e.target.checked}:i))}/><Input value={item.text} onChange={e=>onChange(items.map(i=>i.id===item.id?{...i,text:e.target.value}:i))} className="border-0 bg-transparent px-0"/><button aria-label="Remover item" onClick={()=>onChange(items.filter(i=>i.id!==item.id))}><Trash2 className="size-4 text-ink-faint"/></button></div>)}</div><Button variant="ghost" size="sm" className="mt-2" onClick={onAdd}><Plus/> Adicionar item</Button></div>; }
function Reflection({event,patch,onSchedule}:{event:StudyEvent;patch:(k:'reflection',f:string,v:unknown)=>void;onSchedule?:()=>void}) { const levels:[Understanding,string][]=[['confused','Ainda confuso'],['partial','Entendi parcialmente'],['good','Entendi bem'],['secure','Seguro']]; return <div className="flex flex-col gap-5"><Writing label="O que aprendi hoje?" value={event.reflection.learned} onChange={v=>patch('reflection','learned',v)}/><Writing label="O que ainda ficou difícil?" value={event.reflection.difficult} onChange={v=>patch('reflection','difficult',v)}/><Writing label="O que preciso praticar?" value={event.reflection.practiceNext} onChange={v=>patch('reflection','practiceNext',v)}/><Writing label="Dúvida para a próxima aula" value={event.reflection.questionsNext} onChange={v=>patch('reflection','questionsNext',v)}/><div><p className="type-label text-ink-muted">Como ficou esse assunto?</p><div className="mt-3 flex flex-wrap gap-2">{levels.map(([id,label])=><button key={id} onClick={()=>patch('reflection','understanding',id)} className={`min-h-10 border px-3 text-xs ${event.reflection.understanding===id?'border-ink bg-ink text-paper':'border-rule text-ink-muted'}`}>{label}</button>)}</div></div>{onSchedule&&event.reflection.practiceNext?<Button variant="outline" onClick={onSchedule}><CalendarDays/> Agendar revisão</Button>:null}</div>; }
function Resources({event,notes,materials,boards,onUpdate}:{event:StudyEvent;notes:typeof NO_NOTES;materials:typeof NO_MATERIAL;boards:typeof EMPTY_BOARDS;onUpdate:(p:Partial<StudyEvent>)=>void}) { const options=[...notes.map(n=>({kind:'note' as const,id:n.id,label:n.title})),...materials.map(m=>({kind:'material' as const,id:m.id,label:m.title})),...boards.map(b=>({kind:'board' as const,id:b.id,label:b.title})),{kind:'content' as const,id:'escalas-maiores',label:'Escalas maiores',href:'/escalas-maiores'},{kind:'content' as const,id:'tom-e-semitom',label:'Tom e semitom',href:'/tom-e-semitom'},{kind:'content' as const,id:'laboratorio-da-nota',label:'Laboratório da Nota',href:'/laboratorio-da-nota'}]; return <div><p className="type-label text-ink-muted">Recursos relacionados</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{options.map(o=>{const linked=event.resources.some(r=>r.kind===o.kind&&r.id===o.id);return <label key={`${o.kind}-${o.id}`} className="flex min-h-10 items-center gap-3 border-b border-rule py-2 text-sm"><input type="checkbox" checked={linked} onChange={()=>onUpdate({resources:linked?event.resources.filter(r=>!(r.kind===o.kind&&r.id===o.id)):[...event.resources,o]})}/><span className="flex-1 truncate">{o.label}</span>{'href' in o?<Link href={o.href} className="text-xs text-brass">Abrir</Link>:null}</label>})}</div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/caderno?assunto=${encodeURIComponent(event.topic)}&agenda=${event.id}`} className={buttonClass({variant:'ghost',size:'sm'})}>Nova anotação</Link><Link href="/atelie-de-partitura" className={buttonClass({variant:'ghost',size:'sm'})}>Novo quadro</Link><Link href="/material" className={buttonClass({variant:'ghost',size:'sm'})}>Adicionar material</Link></div></div>; }
function scheduleReview(source:StudyEvent,onAdd:(e:StudyEvent)=>void) { const start=new Date();start.setDate(start.getDate()+1);start.setHours(19,0,0,0);const end=new Date(start.getTime()+20*60000);const now=Date.now();onAdd({...source,id:uid(),type:'review',title:`Revisão — ${source.topic||source.title}`,startAt:start.toISOString(),endAt:end.toISOString(),status:'planned',recurrence:null,teacher:'',location:'',note:source.reflection.practiceNext,preparation:{review:source.reflection.practiceNext,questions:[]},content:{subjects:'',notes:'',examples:'',exercises:'',concepts:''},reflection:{learned:'',difficult:'',practiceNext:'',questionsNext:'',understanding:null,completedAt:null},homework:[],resources:source.resources,createdAt:now,updatedAt:now}); }
