"use client";
import * as React from "react";
import { BookOpen, Eye, Link2, TriangleAlert } from "lucide-react";
import { cn } from "@/lib/utils";

export function TeachingBlock({label,children,tone="note"}:{label:string;children:React.ReactNode;tone?:"note"|"mistake"|"memory"}) { const Icon=tone==="mistake"?TriangleAlert:tone==="memory"?BookOpen:Eye; return <aside className={cn("border-l pl-4",tone==="mistake"?"border-clay":tone==="memory"?"border-brass":"border-rule-strong")}><p className="type-label flex items-center gap-2 text-ink-faint"><Icon className="size-3.5"/>{label}</p><div className="mt-2 text-sm leading-6 text-ink-soft">{children}</div></aside>; }
export function Deeper({children}:{children:React.ReactNode}) { return <details className="border-y border-rule/70 py-4"><summary className="cursor-pointer text-sm font-semibold text-ink">Aprofundar</summary><div className="mt-3 text-sm leading-7 text-ink-muted">{children}</div></details>; }
export function CommonMistake({claim,correction}:{claim:string;correction:string}) { return <TeachingBlock label="Erro comum" tone="mistake"><p>“{claim}”</p><p className="mt-2">{correction}</p></TeachingBlock>; }
export function Memory({items}:{items:string[]}) { return <TeachingBlock label="Para memorizar" tone="memory"><p className="display text-lg font-semibold text-ink">{items.join(" · ")}</p></TeachingBlock>; }
export function Connection({children}:{children:React.ReactNode}) { return <TeachingBlock label="Conexão"><span className="inline-flex"><Link2 className="mr-2 mt-1 size-3.5 text-brass"/></span>{children}</TeachingBlock>; }
export function ConceptChallenge({question,options,answer,explanation}:{question:string;options:string[];answer:string;explanation:string}) { const [given,setGiven]=React.useState<string|null>(null);return <div className="border-t border-rule pt-5"><p className="type-label text-ink-faint">Antes de continuar</p><p className="display mt-2 text-lg font-semibold">{question}</p><div className="mt-4 flex flex-wrap gap-2">{options.map(o=><button key={o} disabled={given!==null} onClick={()=>setGiven(o)} className={cn("min-h-10 border px-4 text-sm",given===null?"border-rule hover:border-brass":o===answer?"border-sage bg-sage-wash text-sage":o===given?"border-clay bg-clay-wash text-clay":"border-rule text-ink-faint")}>{o}</button>)}</div>{given?<p className="mt-3 text-sm text-ink-muted">{given===answer?"Correto. ":`A resposta é ${answer}. `}{explanation}</p>:null}</div>; }
