"use client";
import * as React from "react";
import Link from "next/link";
import { Staff } from "@/components/music/staff";
import { ConceptChallenge, Connection, Deeper, Memory, TeachingBlock } from "./blocks";
import { noteAtSlot, noteName } from "@/lib/music/notes";
import { buttonClass } from "@/components/ui/button";

const lessons:Record<string,{essential:string;observe:string;memory:string;deeper:string,next?:[string,string]}>= {
 partitura:{essential:'A partitura é uma representação escrita da música. Ela organiza símbolos no tempo e na altura para que a música possa ser lida e reconstruída.',observe:'O pentagrama sustenta as notas; a clave dá referência às posições; a leitura segue da esquerda para a direita.',memory:'Partitura é música representada por escrito.',deeper:'Uma partitura pode registrar ritmo, dinâmica e articulação. Nesta etapa, o foco é a altura das notas.',next:['Pentagrama','/fundamentos/pentagrama']},
 pentagrama:{essential:'O pentagrama tem cinco linhas e quatro espaços. Cada passo vertical leva à nota natural seguinte.',observe:'Linhas e espaços são contados de baixo para cima. A posição mais alta representa uma nota mais aguda.',memory:'Cinco linhas, quatro espaços; conte sempre de baixo para cima.',deeper:'Posições fora das cinco linhas usam linhas suplementares, sem mudar a sequência das notas.',next:['Clave de Sol','/fundamentos/clave']},
 clave:{essential:'A clave transforma linhas vazias em posições com nomes. Na clave de Sol, a segunda linha é a referência Sol.',observe:'A espiral da clave envolve a segunda linha do pentagrama.',memory:'Na clave de Sol, a segunda linha é Sol.',deeper:'Outras claves mudam a referência e, portanto, o nome das mesmas posições. O Caderno trabalha agora apenas com a clave de Sol.',next:['Leitura de notas','/leitura-de-notas']},
};
export function FundamentalLesson({slug}:{slug:string}){const lesson=lessons[slug];const [slot,setSlot]=React.useState(2);if(!lesson)return null;return <section className="flex flex-col gap-6 border-y border-rule py-7"><div><p className="type-label text-brass">Professor Mode · Essencial</p><p className="mt-3 max-w-2xl text-sm leading-7 text-ink-soft">{lesson.essential}</p></div><TeachingBlock label="Observe">{lesson.observe}</TeachingBlock>{slug==='pentagrama'?<div><p className="type-label text-ink-faint">Explore as posições</p><div className="mt-3 flex flex-wrap gap-1">{Array.from({length:9},(_,i)=><button key={i} onClick={()=>setSlot(i)} className={`min-h-9 border px-2 text-xs ${slot===i?'border-brass bg-brass-wash':'border-rule'}`}>{i%2===0?`${i/2+1}ª linha`:`${(i+1)/2}º espaço`}</button>)}</div><Staff notes={[{note:noteAtSlot(slot),state:'query',label:noteName(noteAtSlot(slot))}]} ariaLabel={`${noteName(noteAtSlot(slot))} na posição selecionada`} className="mt-4"/></div>:null}{slug==='clave'?<ConceptChallenge question="Qual nota a segunda linha representa na clave de Sol?" options={['Mi','Sol','Si']} answer="Sol" explanation="A espiral da clave envolve justamente essa linha."/>:null}<Memory items={[lesson.memory]}/><Connection>O próximo conceito usa esta ideia: {lesson.next?.[0]??'leitura musical'}.</Connection><Deeper>{lesson.deeper}</Deeper>{lesson.next?<div><p className="type-label text-ink-faint">Próximo passo sugerido</p><Link href={lesson.next[1]} className={buttonClass({variant:'ghost',className:'mt-2'})}>{lesson.next[0]} →</Link></div>:null}</section>}
